"""add_manager_id_to_tasks

Revision ID: 617f11491f16
Revises: 79cb0f455062
Create Date: 2026-06-18 22:21:17.786013

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '617f11491f16'
down_revision: str | Sequence[str] | None = '79cb0f455062'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_manager_id_users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_manager_id_users', type_='foreignkey')
        batch_op.drop_column('manager_id')
    # ### end Alembic commands ###
