"""Initial schema setup

Revision ID: 79cb0f455062
Revises: 
Create Date: 2026-06-17 12:29:10.235269

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '79cb0f455062'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
