from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import Dict, Any, List
import datetime
from .models import User, Document, Task, AgentLog, Department

def get_system_analytics(db: Session, current_user: User = None) -> Dict[str, Any]:
    # 1. Resolve scoping based on role
    role = current_user.role if current_user else "Employee"
    
    if not current_user or role == "Admin":
        scoped_users = db.query(User).all()
        scoped_docs = db.query(Document).all()
        scoped_tasks = db.query(Task).all()
        scoped_logs = db.query(AgentLog).all()
    else:
        # Determine team user IDs
        if role == "Manager":
            subordinates = db.query(User).filter(User.manager_id == current_user.id).all()
            scoped_users = [current_user] + subordinates
        else: # Employee
            if current_user.manager_id:
                teammates = db.query(User).filter(User.manager_id == current_user.manager_id).all()
                manager = db.query(User).filter(User.id == current_user.manager_id).first()
                scoped_users = list(set([current_user] + teammates + ([manager] if manager else [])))
            else:
                scoped_users = [current_user]
                
        user_ids = [u.id for u in scoped_users]
        dept_ids = list(set([u.department_id for u in scoped_users if u.department_id is not None]))
        
        # Scoped documents: same departments or uploaded by team members
        if dept_ids:
            scoped_docs = db.query(Document).filter(
                (Document.department_id.in_(dept_ids)) | (Document.uploaded_by.in_(user_ids))
            ).all()
        else:
            scoped_docs = db.query(Document).filter(Document.uploaded_by.in_(user_ids)).all()
            
        # Scoped tasks: assigned to team members
        scoped_tasks = db.query(Task).filter(Task.assigned_to.in_(user_ids)).all()
        
        # Scoped logs: generated by team members
        scoped_logs = db.query(AgentLog).filter(AgentLog.user_id.in_(user_ids)).all()

    # Now calculate analytics metrics from the scoped collections
    total_users = len(scoped_users)
    total_docs = len(scoped_docs)
    total_tasks = len(scoped_tasks)
    total_logs = len(scoped_logs)
    
    # Document types breakdown
    docs_by_type = {}
    for doc in scoped_docs:
        ftype = doc.file_type or "Unknown"
        docs_by_type[ftype] = docs_by_type.get(ftype, 0) + 1
        
    # Task status breakdown
    completed_tasks = sum(1 for t in scoped_tasks if t.status == "Completed")
    pending_tasks = sum(1 for t in scoped_tasks if t.status == "Pending")
    in_progress_tasks = sum(1 for t in scoped_tasks if t.status == "In_Progress")
    
    # Department distribution (If Admin, show all. If Manager/Employee, only show their departments)
    dept_distribution = []
    if not current_user or role == "Admin":
        depts = db.query(Department).all()
        dept_ids = []
    else:
        depts = db.query(Department).filter(Department.id.in_(dept_ids)).all() if dept_ids else []
        
    for dept in depts:
        u_count = db.query(User).filter(User.department_id == dept.id).count()
        d_count = db.query(Document).filter(Document.department_id == dept.id).count()
        dept_distribution.append({
            "name": dept.name,
            "users": u_count,
            "documents": d_count
        })
        
    # Search logs (latest 10 logs)
    latest_logs = []
    sorted_logs = sorted(scoped_logs, key=lambda l: l.timestamp or datetime.datetime.min, reverse=True)[:10]
    user_map = {u.id: u for u in db.query(User).all()}
    
    for log in sorted_logs:
        user_email = user_map[log.user_id].email if log.user_id in user_map else "Unknown"
        latest_logs.append({
            "id": log.id,
            "user": user_email,
            "query": log.query,
            "timestamp": log.timestamp.strftime("%Y-%m-%d %H:%M:%S") if log.timestamp else "N/A"
        })
        
    # Documentation health score
    gap_count = sum(1 for log in sorted_logs if "no documents match" in log.response.lower() or "simulation mode" in log.response.lower())
    docs_health = 100
    if len(sorted_logs) > 0:
        docs_health = max(0, int(100 - (gap_count / len(sorted_logs)) * 100))
        
    # Team Workload & Detailed Tasks lists for subordinates
    team_workload = []
    if current_user and role in ("Manager", "Admin"):
        for member in scoped_users:
            pending = db.query(Task).filter(Task.assigned_to == member.id, Task.status == "Pending").count()
            in_progress = db.query(Task).filter(Task.assigned_to == member.id, Task.status == "In_Progress").count()
            completed = db.query(Task).filter(Task.assigned_to == member.id, Task.status == "Completed").count()
            
            # Fetch actual tasks list for each employee
            member_tasks = db.query(Task).filter(Task.assigned_to == member.id).all()
            member_tasks_list = [{
                "id": t.id,
                "title": t.title,
                "status": t.status,
                "description": t.description or ""
            } for t in member_tasks]
            
            team_workload.append({
                "user_id": member.id,
                "name": member.full_name or member.email,
                "email": member.email,
                "role": member.role,
                "pending": pending,
                "in_progress": in_progress,
                "completed": completed,
                "tasks": member_tasks_list
            })
            
    # Team Details
    team_details = {}
    if current_user:
        if role == "Manager":
            manager_dept = db.query(Department).filter(Department.id == current_user.department_id).first()
            team_members = []
            for u in scoped_users:
                u_dept = db.query(Department).filter(Department.id == u.department_id).first()
                team_members.append({
                    "id": u.id,
                    "name": u.full_name or u.email,
                    "email": u.email,
                    "role": u.role,
                    "department": u_dept.name if u_dept else "General",
                    "is_manager": u.id == current_user.id
                })
            team_details = {
                "role": "Manager",
                "team_size": len(team_members),
                "team_members": team_members
            }
        elif role == "Admin":
            admin_teams = []
            managers = db.query(User).filter(User.role == "Manager").all()
            total_members_count = 0
            for mgr in managers:
                mgr_dept = db.query(Department).filter(Department.id == mgr.department_id).first()
                subordinates = db.query(User).filter(User.manager_id == mgr.id).all()
                mgr_team_users = [mgr] + subordinates
                members_list = []
                for u in mgr_team_users:
                    u_dept = db.query(Department).filter(Department.id == u.department_id).first()
                    members_list.append({
                        "id": u.id,
                        "name": u.full_name or u.email,
                        "email": u.email,
                        "role": u.role,
                        "department": u_dept.name if u_dept else "General",
                        "is_manager": u.id == mgr.id
                    })
                total_members_count += len(members_list)
                admin_teams.append({
                    "manager_id": mgr.id,
                    "manager_name": mgr.full_name or mgr.email,
                    "manager_email": mgr.email,
                    "department": mgr_dept.name if mgr_dept else "General",
                    "members": members_list,
                    "team_size": len(members_list)
                })
            team_details = {
                "role": "Admin",
                "total_teams": len(admin_teams),
                "total_team_members": total_members_count,
                "teams": admin_teams
            }
        elif role == "Employee":
            team_details = {
                "role": "Employee",
                "team_size": len(scoped_users)
            }
            
    return {
        "stats": {
            "total_users": total_users,
            "total_documents": total_docs,
            "total_tasks": total_tasks,
            "total_searches": total_logs
        },
        "docs_by_type": docs_by_type,
        "task_status": {
            "Completed": completed_tasks,
            "Pending": pending_tasks,
            "In_Progress": in_progress_tasks
        },
        "department_activity": dept_distribution,
        "latest_searches": latest_logs,
        "documentation_health": docs_health,
        "team_workload": team_workload,
        "team_details": team_details
    }
